"""m6b requests client portal support

Revision ID: 8a1be8237915
Revises: f388fbe07700
Create Date: 2026-09-19 22:37:18.288966
"""
from alembic import op
import sqlalchemy as sa


revision = '8a1be8237915'
down_revision = 'f388fbe07700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('module_key', sa.String(length=32), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_operator_id', sa.Uuid(), nullable=True),
    sa.Column('first_response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_assigned_operator_id'), ['assigned_operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index('ix_support_tickets_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('support_comments',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('is_operator', sa.Boolean(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_comments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_comments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('portal_login_tokens',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_login_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_login_tokens_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_login_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_login_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('portal_messages',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_by_practice_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_by_client_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_messages', schema=None) as batch_op:
        batch_op.create_index('ix_portal_messages_client_created', ['client_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_messages_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('portal_sessions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_sessions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_portal_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('request_packs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_packs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_packs_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_packs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_packs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_request_packs_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_packs_token_hash'), ['token_hash'], unique=True)

    op.create_table('request_items',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('client_note', sa.String(length=600), nullable=True),
    sa.Column('rejection_reason', sa.String(length=600), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pack_id'], ['request_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_items_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index('ix_request_items_pack_key', ['pack_id', 'key'], unique=True)
        batch_op.create_index(batch_op.f('ix_request_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_items_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_client', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('visible_to_client')

    with op.batch_alter_table('request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_request_items_status'))
        batch_op.drop_index('ix_request_items_pack_key')
        batch_op.drop_index(batch_op.f('ix_request_items_pack_id'))

    op.drop_table('request_items')
    with op.batch_alter_table('request_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_packs_token_hash'))
        batch_op.drop_index('ix_request_packs_tenant_status')
        batch_op.drop_index(batch_op.f('ix_request_packs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_request_packs_status'))
        batch_op.drop_index(batch_op.f('ix_request_packs_due_on'))
        batch_op.drop_index(batch_op.f('ix_request_packs_client_id'))

    op.drop_table('request_packs')
    with op.batch_alter_table('portal_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_portal_sessions_jti'))
        batch_op.drop_index(batch_op.f('ix_portal_sessions_contact_id'))

    op.drop_table('portal_sessions')
    with op.batch_alter_table('portal_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_portal_messages_client_id'))
        batch_op.drop_index('ix_portal_messages_client_created')

    op.drop_table('portal_messages')
    with op.batch_alter_table('portal_login_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_login_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_portal_login_tokens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_portal_login_tokens_contact_id'))

    op.drop_table('portal_login_tokens')
    with op.batch_alter_table('support_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_comments_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_comments_tenant_id'))

    op.drop_table('support_comments')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_tenant_id'))
        batch_op.drop_index('ix_support_tickets_status_priority')
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_assigned_operator_id'))

    op.drop_table('support_tickets')
    # ### end Alembic commands ###
