"""m6a start and practice

Revision ID: f388fbe07700
Revises: dea2ea6532a8
Create Date: 2026-09-19 18:59:54.560210
"""
from alembic import op
import sqlalchemy as sa


revision = 'f388fbe07700'
down_revision = 'dea2ea6532a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('start_services',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basis', sa.String(length=12), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('gst', sa.Boolean(), nullable=False),
    sa.Column('entity_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('start_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_start_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('practice_recurring_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name_template', sa.String(length=200), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.String(length=12), nullable=False),
    sa.Column('month_offset', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('advance_days', sa.Integer(), nullable=False),
    sa.Column('assignee_membership_id', sa.Uuid(), nullable=True),
    sa.Column('budget_minutes', sa.Integer(), nullable=True),
    sa.Column('fee_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_period_label', sa.String(length=40), nullable=True),
    sa.Column('next_due_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_recurring_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_recurring_jobs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_recurring_jobs_next_due_on'), ['next_due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_recurring_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('onboardings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('primary_contact_id', sa.Uuid(), nullable=True),
    sa.Column('owner_membership_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdraw_reason', sa.String(length=300), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('gates', sa.JSON(), nullable=False),
    sa.Column('sign_agreement_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_total_cents', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboardings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboardings_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboardings_owner_membership_id'), ['owner_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboardings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboardings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_onboardings_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboardings_token_hash'), ['token_hash'], unique=True)

    op.create_table('practice_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('lodgement_due', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assignee_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_membership_id', sa.Uuid(), nullable=True),
    sa.Column('budget_minutes', sa.Integer(), nullable=True),
    sa.Column('fee_cents', sa.Integer(), nullable=True),
    sa.Column('recurring_job_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_job_id'], ['practice_recurring_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_jobs_assignee_membership_id'), ['assignee_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_lodgement_due'), ['lodgement_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_recurring_job_id'), ['recurring_job_id'], unique=False)
        batch_op.create_index('ix_practice_jobs_recurring_period', ['recurring_job_id', 'period_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_practice_jobs_tenant_status_due', ['tenant_id', 'status', 'due_on'], unique=False)

    op.create_table('onboarding_stages',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=120), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboardings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_stages', schema=None) as batch_op:
        batch_op.create_index('ix_onboarding_stages_onb_number', ['onboarding_id', 'number'], unique=True)
        batch_op.create_index(batch_op.f('ix_onboarding_stages_onboarding_id'), ['onboarding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_stages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('practice_time_entries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('worked_on', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['practice_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_time_entries_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_time_entries_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_time_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_time_entries_worked_on'), ['worked_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_time_entries_worked_on'))
        batch_op.drop_index(batch_op.f('ix_practice_time_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_practice_time_entries_membership_id'))
        batch_op.drop_index(batch_op.f('ix_practice_time_entries_job_id'))

    op.drop_table('practice_time_entries')
    with op.batch_alter_table('onboarding_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_stages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_stages_onboarding_id'))
        batch_op.drop_index('ix_onboarding_stages_onb_number')

    op.drop_table('onboarding_stages')
    with op.batch_alter_table('practice_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_jobs_tenant_status_due')
        batch_op.drop_index(batch_op.f('ix_practice_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_practice_jobs_status'))
        batch_op.drop_index('ix_practice_jobs_recurring_period')
        batch_op.drop_index(batch_op.f('ix_practice_jobs_recurring_job_id'))
        batch_op.drop_index(batch_op.f('ix_practice_jobs_lodgement_due'))
        batch_op.drop_index(batch_op.f('ix_practice_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_practice_jobs_due_on'))
        batch_op.drop_index(batch_op.f('ix_practice_jobs_client_id'))
        batch_op.drop_index(batch_op.f('ix_practice_jobs_assignee_membership_id'))

    op.drop_table('practice_jobs')
    with op.batch_alter_table('onboardings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboardings_token_hash'))
        batch_op.drop_index('ix_onboardings_tenant_status')
        batch_op.drop_index(batch_op.f('ix_onboardings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_onboardings_status'))
        batch_op.drop_index(batch_op.f('ix_onboardings_owner_membership_id'))
        batch_op.drop_index(batch_op.f('ix_onboardings_client_id'))

    op.drop_table('onboardings')
    with op.batch_alter_table('practice_recurring_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_recurring_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_practice_recurring_jobs_next_due_on'))
        batch_op.drop_index(batch_op.f('ix_practice_recurring_jobs_client_id'))

    op.drop_table('practice_recurring_jobs')
    with op.batch_alter_table('start_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_start_services_tenant_id'))

    op.drop_table('start_services')
    # ### end Alembic commands ###
