"""contact portal_access

Revision ID: 9416dc583c17
Revises: 8a1be8237915
Create Date: 2026-09-19 22:40:30.488630
"""
from alembic import op
import sqlalchemy as sa


revision = '9416dc583c17'
down_revision = '8a1be8237915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_access', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('portal_access')

    # ### end Alembic commands ###
