"""m6c workpapers advisory academy lending

Revision ID: ff42b6af7897
Revises: 9416dc583c17
Create Date: 2026-09-19 23:01:12.356036
"""
from alembic import op
import sqlalchemy as sa


revision = 'ff42b6af7897'
down_revision = '9416dc583c17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy_courses',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('pass_mark', sa.Integer(), nullable=False),
    sa.Column('certificate', sa.Boolean(), nullable=False),
    sa.Column('valid_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_courses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_courses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('academy_lessons',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=600), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_lessons_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_lessons_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('academy_requirements',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('frequency_months', sa.Integer(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_requirements_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_requirements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ledger_connections',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('external_tenant_id', sa.String(length=120), nullable=True),
    sa.Column('external_name', sa.String(length=200), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('connected_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connected_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_connections_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_connections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_connections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('academy_enrolments',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('completed_lessons', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['academy_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_enrolments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_enrolments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_enrolments_due_on'), ['due_on'], unique=False)
        batch_op.create_index('ix_academy_enrolments_member_course', ['membership_id', 'course_id', 'requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_enrolments_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_enrolments_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_enrolments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_enrolments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('academy_attempts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('enrolment_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['enrolment_id'], ['academy_enrolments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['academy_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_attempts_enrolment_id'), ['enrolment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_attempts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('academy_certificates',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('enrolment_id', sa.Uuid(), nullable=True),
    sa.Column('serial', sa.String(length=40), nullable=False),
    sa.Column('course_title', sa.String(length=220), nullable=False),
    sa.Column('member_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrolment_id'], ['academy_enrolments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_certificates_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_certificates_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_certificates_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_certificates_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_academy_certificates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lending_applications',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('rate_bps', sa.Integer(), nullable=True),
    sa.Column('repayment_cents', sa.Integer(), nullable=True),
    sa.Column('lender', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('owner_membership_id', sa.Uuid(), nullable=True),
    sa.Column('request_pack_id', sa.Uuid(), nullable=True),
    sa.Column('serviceability', sa.JSON(), nullable=False),
    sa.Column('readiness_pct', sa.Integer(), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=300), nullable=True),
    sa.Column('expected_settlement', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_pack_id'], ['request_packs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lending_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lending_applications_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_applications_expected_settlement'), ['expected_settlement'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_applications_owner_membership_id'), ['owner_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_applications_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_lending_applications_request_pack_id'), ['request_pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_applications_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_applications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_lending_applications_tenant_stage', ['tenant_id', 'stage'], unique=False)

    op.create_table('workpaper_packs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('pack_type', sa.String(length=40), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preparer_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_membership_id', sa.Uuid(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('lodged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lodgement_ref', sa.String(length=120), nullable=True),
    sa.Column('materiality_cents', sa.Integer(), nullable=True),
    sa.Column('ledger_source', sa.String(length=20), nullable=False),
    sa.Column('ledger_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ledger_ref', sa.String(length=200), nullable=True),
    sa.Column('seal_sha256', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['practice_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preparer_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signed_off_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workpaper_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workpaper_packs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_packs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_packs_pack_type'), ['pack_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_packs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_packs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_workpaper_packs_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('advisory_snapshots',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('as_at', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('workpaper_id', sa.Uuid(), nullable=True),
    sa.Column('revenue_cents', sa.Integer(), nullable=True),
    sa.Column('gross_profit_cents', sa.Integer(), nullable=True),
    sa.Column('expenses_cents', sa.Integer(), nullable=True),
    sa.Column('net_profit_cents', sa.Integer(), nullable=True),
    sa.Column('cash_cents', sa.Integer(), nullable=True),
    sa.Column('receivables_cents', sa.Integer(), nullable=True),
    sa.Column('payables_cents', sa.Integer(), nullable=True),
    sa.Column('inventory_cents', sa.Integer(), nullable=True),
    sa.Column('debt_cents', sa.Integer(), nullable=True),
    sa.Column('equity_cents', sa.Integer(), nullable=True),
    sa.Column('tax_provision_cents', sa.Integer(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_band', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workpaper_id'], ['workpaper_packs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisory_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisory_snapshots_as_at'), ['as_at'], unique=False)
        batch_op.create_index('ix_advisory_snapshots_client_asat', ['client_id', 'as_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_snapshots_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lending_conditions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('owner_side', sa.String(length=10), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfied_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=600), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['lending_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['satisfied_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lending_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lending_conditions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_conditions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_conditions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lending_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('from_stage', sa.String(length=16), nullable=True),
    sa.Column('to_stage', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['lending_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lending_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lending_events_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lending_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workpaper_items',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=40), nullable=True),
    sa.Column('value_cents', sa.Integer(), nullable=True),
    sa.Column('prior_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cents', sa.Integer(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_state', sa.String(length=10), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('workings', sa.Text(), nullable=True),
    sa.Column('query', sa.String(length=600), nullable=True),
    sa.Column('prepared_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pack_id'], ['workpaper_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workpaper_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workpaper_items_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index('ix_workpaper_items_pack_key', ['pack_id', 'key'], unique=True)
        batch_op.create_index(batch_op.f('ix_workpaper_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('advisory_alerts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('benchmark', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('dismissed_reason', sa.String(length=300), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['advisory_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisory_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisory_alerts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_alerts_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_alerts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('advisory_meetings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('agenda', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('prepared_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prepared_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['advisory_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisory_meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisory_meetings_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_meetings_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_meetings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_meetings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workpaper_issues',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('raised_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.String(length=600), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['workpaper_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['workpaper_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workpaper_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workpaper_issues_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_issues_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_issues_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('advisory_actions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('owner_side', sa.String(length=10), nullable=False),
    sa.Column('owner_membership_id', sa.Uuid(), nullable=True),
    sa.Column('owner_label', sa.String(length=200), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('visible_to_client', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['advisory_alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['advisory_meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisory_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisory_actions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_actions_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_actions_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_actions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_actions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisory_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisory_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_advisory_actions_status'))
        batch_op.drop_index(batch_op.f('ix_advisory_actions_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_advisory_actions_due_on'))
        batch_op.drop_index(batch_op.f('ix_advisory_actions_client_id'))

    op.drop_table('advisory_actions')
    with op.batch_alter_table('workpaper_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workpaper_issues_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_issues_status'))
        batch_op.drop_index(batch_op.f('ix_workpaper_issues_pack_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_issues_item_id'))

    op.drop_table('workpaper_issues')
    with op.batch_alter_table('advisory_meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisory_meetings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_advisory_meetings_status'))
        batch_op.drop_index(batch_op.f('ix_advisory_meetings_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_advisory_meetings_client_id'))

    op.drop_table('advisory_meetings')
    with op.batch_alter_table('advisory_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisory_alerts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_advisory_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_advisory_alerts_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_advisory_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_advisory_alerts_client_id'))

    op.drop_table('advisory_alerts')
    with op.batch_alter_table('workpaper_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workpaper_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_items_status'))
        batch_op.drop_index('ix_workpaper_items_pack_key')
        batch_op.drop_index(batch_op.f('ix_workpaper_items_pack_id'))

    op.drop_table('workpaper_items')
    with op.batch_alter_table('lending_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lending_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lending_events_application_id'))

    op.drop_table('lending_events')
    with op.batch_alter_table('lending_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lending_conditions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lending_conditions_status'))
        batch_op.drop_index(batch_op.f('ix_lending_conditions_application_id'))

    op.drop_table('lending_conditions')
    with op.batch_alter_table('advisory_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisory_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_advisory_snapshots_client_id'))
        batch_op.drop_index('ix_advisory_snapshots_client_asat')
        batch_op.drop_index(batch_op.f('ix_advisory_snapshots_as_at'))

    op.drop_table('advisory_snapshots')
    with op.batch_alter_table('workpaper_packs', schema=None) as batch_op:
        batch_op.drop_index('ix_workpaper_packs_tenant_status')
        batch_op.drop_index(batch_op.f('ix_workpaper_packs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_packs_status'))
        batch_op.drop_index(batch_op.f('ix_workpaper_packs_pack_type'))
        batch_op.drop_index(batch_op.f('ix_workpaper_packs_job_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_packs_client_id'))

    op.drop_table('workpaper_packs')
    with op.batch_alter_table('lending_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_lending_applications_tenant_stage')
        batch_op.drop_index(batch_op.f('ix_lending_applications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lending_applications_stage'))
        batch_op.drop_index(batch_op.f('ix_lending_applications_request_pack_id'))
        batch_op.drop_index(batch_op.f('ix_lending_applications_reference'))
        batch_op.drop_index(batch_op.f('ix_lending_applications_owner_membership_id'))
        batch_op.drop_index(batch_op.f('ix_lending_applications_expected_settlement'))
        batch_op.drop_index(batch_op.f('ix_lending_applications_client_id'))

    op.drop_table('lending_applications')
    with op.batch_alter_table('academy_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_certificates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_academy_certificates_serial'))
        batch_op.drop_index(batch_op.f('ix_academy_certificates_membership_id'))
        batch_op.drop_index(batch_op.f('ix_academy_certificates_expires_on'))
        batch_op.drop_index(batch_op.f('ix_academy_certificates_course_id'))

    op.drop_table('academy_certificates')
    with op.batch_alter_table('academy_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_attempts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_academy_attempts_enrolment_id'))

    op.drop_table('academy_attempts')
    with op.batch_alter_table('academy_enrolments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_enrolments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_academy_enrolments_status'))
        batch_op.drop_index(batch_op.f('ix_academy_enrolments_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_academy_enrolments_membership_id'))
        batch_op.drop_index('ix_academy_enrolments_member_course')
        batch_op.drop_index(batch_op.f('ix_academy_enrolments_due_on'))
        batch_op.drop_index(batch_op.f('ix_academy_enrolments_course_id'))

    op.drop_table('academy_enrolments')
    with op.batch_alter_table('ledger_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_connections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_connections_status'))
        batch_op.drop_index(batch_op.f('ix_ledger_connections_client_id'))

    op.drop_table('ledger_connections')
    with op.batch_alter_table('academy_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_requirements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_academy_requirements_course_id'))

    op.drop_table('academy_requirements')
    with op.batch_alter_table('academy_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_lessons_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_academy_lessons_course_id'))

    op.drop_table('academy_lessons')
    with op.batch_alter_table('academy_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_courses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_academy_courses_status'))
        batch_op.drop_index(batch_op.f('ix_academy_courses_category'))

    op.drop_table('academy_courses')
    # ### end Alembic commands ###
