"""crm core: clients, contacts, relationships, timeline, tasks, notes, segments, import jobs

Revision ID: 142aa9fcb1af
Revises: d6eca17062bf
Create Date: 2026-09-19 17:53:28.209200
"""
from alembic import op
import sqlalchemy as sa


revision = '142aa9fcb1af'
down_revision = 'd6eca17062bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('from_type', sa.String(length=10), nullable=False),
    sa.Column('from_id', sa.Uuid(), nullable=False),
    sa.Column('to_type', sa.String(length=10), nullable=False),
    sa.Column('to_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_from_id'), ['from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_to_id'), ['to_id'], unique=False)

    op.create_table('clients',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_normalised', sa.String(length=300), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.Column('abn', sa.String(length=11), nullable=True),
    sa.Column('acn', sa.String(length=9), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('owner_membership_id', sa.Uuid(), nullable=True),
    sa.Column('risk_rating', sa.String(length=10), nullable=True),
    sa.Column('risk_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('suburb', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('custom', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_abn'), ['abn'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name_normalised'), ['name_normalised'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_owner_membership_id'), ['owner_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_stage'), ['stage'], unique=False)
        batch_op.create_index('ix_clients_tenant_abn', ['tenant_id', 'abn'], unique=False)
        batch_op.create_index('ix_clients_tenant_ext', ['tenant_id', 'external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_clients_tenant_name', ['tenant_id', 'name_normalised'], unique=False)
        batch_op.create_index('ix_clients_tenant_stage', ['tenant_id', 'stage'], unique=False)

    op.create_table('import_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('segments',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('contacts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('portal_user_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notes',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_membership_id', sa.Uuid(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tasks',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('assignee_membership_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('module_key', sa.String(length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_membership_id'), ['assignee_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('module_key', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('actor_membership_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_timeline_tenant_client_time', ['tenant_id', 'client_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_tenant_client_time')
        batch_op.drop_index(batch_op.f('ix_timeline_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_client_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_client_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_membership_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notes_client_id'))

    op.drop_table('notes')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_client_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_tenant_id'))

    op.drop_table('segments')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_tenant_id'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_tenant_stage')
        batch_op.drop_index('ix_clients_tenant_name')
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))
        batch_op.drop_index('ix_clients_tenant_ext')
        batch_op.drop_index('ix_clients_tenant_abn')
        batch_op.drop_index(batch_op.f('ix_clients_stage'))
        batch_op.drop_index(batch_op.f('ix_clients_owner_membership_id'))
        batch_op.drop_index(batch_op.f('ix_clients_name_normalised'))
        batch_op.drop_index(batch_op.f('ix_clients_abn'))

    op.drop_table('clients')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_to_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_from_id'))

    op.drop_table('relationships')
    # ### end Alembic commands ###
