"""m7 documents and practice billing

Revision ID: dcad362a1f0e
Revises: ff42b6af7897
Create Date: 2026-09-19 23:15:29.053064
"""
from alembic import op
import sqlalchemy as sa


revision = 'dcad362a1f0e'
down_revision = 'ff42b6af7897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_retention_policies',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kinds', sa.JSON(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_retention_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('billing_fee_schedules',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=12), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('gst', sa.Boolean(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('terms_days', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_issue_on', sa.Date(), nullable=True),
    sa.Column('last_invoice_period', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_fee_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_fee_schedules_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_fee_schedules_next_issue_on'), ['next_issue_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_fee_schedules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('document_folders',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_folders_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_folders_path'), ['path'], unique=False)
        batch_op.create_index('ix_document_folders_tenant_client_path', ['tenant_id', 'client_id', 'path'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_folders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('document_index',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_source', sa.String(length=16), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('retain_until', sa.Date(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['document_retention_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_index_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_index_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_index_retain_until'), ['retain_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_index_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('billing_invoices',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('gst_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('paid_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fee_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['billing_fee_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['practice_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_fee_schedule_id'), ['fee_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_issued_on'), ['issued_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_billing_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_billing_invoices_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('billing_invoice_lines',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cents', sa.Integer(), nullable=False),
    sa.Column('gst', sa.Boolean(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_invoice_lines_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoice_lines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('billing_payments',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('recorded_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_payments_received_on'), ['received_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_payments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_payments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_payments_received_on'))
        batch_op.drop_index(batch_op.f('ix_billing_payments_invoice_id'))

    op.drop_table('billing_payments')
    with op.batch_alter_table('billing_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_invoice_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_invoice_lines_invoice_id'))

    op.drop_table('billing_invoice_lines')
    with op.batch_alter_table('billing_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_billing_invoices_tenant_status')
        batch_op.drop_index(batch_op.f('ix_billing_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_issued_on'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_fee_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_due_on'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_client_id'))

    op.drop_table('billing_invoices')
    with op.batch_alter_table('document_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_index_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_document_index_retain_until'))
        batch_op.drop_index(batch_op.f('ix_document_index_folder_id'))
        batch_op.drop_index(batch_op.f('ix_document_index_document_id'))

    op.drop_table('document_index')
    with op.batch_alter_table('document_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_folders_tenant_id'))
        batch_op.drop_index('ix_document_folders_tenant_client_path')
        batch_op.drop_index(batch_op.f('ix_document_folders_path'))
        batch_op.drop_index(batch_op.f('ix_document_folders_parent_id'))
        batch_op.drop_index(batch_op.f('ix_document_folders_client_id'))

    op.drop_table('document_folders')
    with op.batch_alter_table('billing_fee_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_fee_schedules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_fee_schedules_next_issue_on'))
        batch_op.drop_index(batch_op.f('ix_billing_fee_schedules_client_id'))

    op.drop_table('billing_fee_schedules')
    with op.batch_alter_table('document_retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_retention_policies_tenant_id'))

    op.drop_table('document_retention_policies')
    # ### end Alembic commands ###
