"""m5 verify and sign

Revision ID: dea2ea6532a8
Revises: 8d8c1f20bfb4
Create Date: 2026-09-19 18:34:26.076057
"""
from alembic import op
import sqlalchemy as sa


revision = 'dea2ea6532a8'
down_revision = '8d8c1f20bfb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('assessed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_next_review_at'), ['next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_risk_tenant_client_current', ['tenant_id', 'client_id', 'superseded_at'], unique=False)

    op.create_table('agreements',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('require_identity', sa.Boolean(), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('sealed_sha256', sa.String(length=64), nullable=True),
    sa.Column('certificate', sa.JSON(), nullable=True),
    sa.Column('chain_head', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agreements_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agreements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agreements_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_agreements_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('screenings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(length=12), nullable=False),
    sa.Column('subject_name', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_decision', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenings_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenings_status'), ['status'], unique=False)
        batch_op.create_index('ix_screenings_tenant_client', ['tenant_id', 'client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('verifications',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(length=12), nullable=False),
    sa.Column('subject_name', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('verification_url', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('started_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_provider_ref'), ['provider_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_status'), ['status'], unique=False)
        batch_op.create_index('ix_verifications_tenant_client', ['tenant_id', 'client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('signers',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.String(length=500), nullable=True),
    sa.Column('signature_kind', sa.String(length=10), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('signature_sha256', sa.String(length=64), nullable=True),
    sa.Column('identity_verification_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signers_agreement_id'), ['agreement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signers_token_hash'), ['token_hash'], unique=True)

    op.create_table('sign_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('signer_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signer_id'], ['signers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('sign_events', schema=None) as batch_op:
        batch_op.create_index('ix_sign_events_agreement_at', ['agreement_id', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_events_agreement_id'), ['agreement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_events_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sign_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sign_events_agreement_id'))
        batch_op.drop_index('ix_sign_events_agreement_at')

    op.drop_table('sign_events')
    with op.batch_alter_table('signers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signers_token_hash'))
        batch_op.drop_index(batch_op.f('ix_signers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_signers_agreement_id'))

    op.drop_table('signers')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_tenant_id'))
        batch_op.drop_index('ix_verifications_tenant_client')
        batch_op.drop_index(batch_op.f('ix_verifications_status'))
        batch_op.drop_index(batch_op.f('ix_verifications_provider_ref'))
        batch_op.drop_index(batch_op.f('ix_verifications_contact_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_client_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_tenant_id'))
        batch_op.drop_index('ix_screenings_tenant_client')
        batch_op.drop_index(batch_op.f('ix_screenings_status'))
        batch_op.drop_index(batch_op.f('ix_screenings_contact_id'))
        batch_op.drop_index(batch_op.f('ix_screenings_client_id'))

    op.drop_table('screenings')
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_index('ix_agreements_tenant_status')
        batch_op.drop_index(batch_op.f('ix_agreements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agreements_status'))
        batch_op.drop_index(batch_op.f('ix_agreements_client_id'))

    op.drop_table('agreements')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_tenant_client_current')
        batch_op.drop_index(batch_op.f('ix_risk_assessments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_next_review_at'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_client_id'))

    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
